name: Pipeline con Pruebas

on:
  push:
    branches:
      - main
      - 'feature/*'

jobs:
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        working-directory: ./app
        run: npm install

      - name: Ejecutar pruebas unitarias
        working-directory: ./app
        run: npm test

      - name: Guardar reporte de cobertura
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./app/coverage/
